version: 2
updates:
  - package-ecosystem: gradle
    directories:
      - /
      - /gradle/build-logic
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /docs
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: /cli/extensions/vscode
    schedule:
      interval: weekly
