package dev.w0fv1.norm.truffle;

import dev.w0fv1.norm.abi.IntrinsicId;
import java.util.Collections;
import java.util.EnumSet;
import java.util.Set;

public final class IntrinsicDispatcher {
  private static final Set<IntrinsicId> SUPPORTED =
      Collections.unmodifiableSet(EnumSet.allOf(IntrinsicId.class));

  private IntrinsicDispatcher() {}

  public static Set<IntrinsicId> supportedIntrinsics() {
    return SUPPORTED;
  }

  static IntrinsicOperation resolve(IntrinsicId intrinsic) {
    return switch (intrinsic) {
      case VALUE_CLASS,
          CLASS_IS_VALUE,
          FIELD_HAS_ANNOTATION,
          FIELD_IDENTITY,
          FIELD_IS_PUBLIC,
          FIELD_BIND,
          FIELD_HANDLE_READ,
          FIELD_HANDLE_WRITE,
          FIELD_WRITE,
          FIELD_COPY,
          CLASS_LITERAL,
          CLASS_NAME,
          CLASS_ANNOTATION,
          CLASS_FIELDS,
          CLASS_FUNCTIONS,
          CLASS_CONSTRUCTORS,
          FIELD_LITERAL,
          FIELD_NAME,
          FIELD_TYPE,
          FIELD_OWNER,
          FIELD_ANNOTATION,
          FIELD_READ,
          FUNCTION_NAME,
          FUNCTION_OWNER,
          FUNCTION_PARAMETERS,
          PARAMETER_NAME,
          PARAMETER_TYPE,
          PARAMETER_FUNCTION,
          CONSTRUCTOR_OWNER,
          FUNCTION_CONTEXT_FUNCTION,
          PARAMETER_CONTEXT_PARAMETER,
          FIELD_CONTEXT_FIELD,
          FUNCTION_INVOCATION_PROCEED,
          FUNCTION_COMPLETION_SUCCEEDED ->
          ReflectionIntrinsicDispatcher.resolve(intrinsic);
      case JSON_ENCODE,
          JSON_DECODE,
          JSON_PARSE,
          JSON_WRITE,
          XML_ENCODE,
          XML_DECODE,
          YAML_ENCODE,
          YAML_DECODE,
          CONFIGURATION_PROPERTIES ->
          SerializationIntrinsicDispatcher.resolve(intrinsic);
      case CONTEXT_CURRENT,
          OBSERVE_FIELDS,
          OBSERVE_FIELD,
          CONTEXT_WITH,
          PRINT_LINE,
          EXPECTED_OUTPUT_LINE,
          AWAIT_CANCELLATION,
          APPLICATION_PACKAGE,
          APPLICATION_DIRECTORY,
          REQUIRE_ARGUMENT,
          PUBLISH_MODULE,
          JAR_INPUT_STREAM_READ,
          JAR_OUTPUT_STREAM_WRITE,
          JAR_OUTPUT_STREAM_FLUSH,
          JAR_STREAM_CLOSE,
          TIME_SYSTEM_CLOCK,
          TIME_CLOCK_NOW ->
          CoreIntrinsicDispatcher.resolve(intrinsic);
      case JAVA_COLLECTION_SIZE,
          JAVA_LIST_GET,
          JAVA_LIST_SET,
          JAVA_LIST_REMOVE,
          JAVA_COLLECTION_CONTAINS,
          JAVA_COLLECTION_ADD,
          JAVA_COLLECTION_REMOVE,
          JAVA_ITERABLE_ITERATOR,
          JAVA_ITERATOR_HAS_NEXT,
          JAVA_ITERATOR_NEXT,
          JAVA_MAP_NEW,
          JAVA_MAP_SIZE,
          JAVA_MAP_CONTAINS_KEY,
          JAVA_MAP_GET,
          JAVA_MAP_PUT,
          JAVA_MAP_REMOVE,
          JAR_INVOKE,
          JAR_INVOKE_VOID ->
          JavaIntrinsicDispatcher.resolve(intrinsic);
      case TO_STRING,
          STRING_BUILDER_CONSTRUCT,
          BUILDER_APPEND,
          BUILDER_TO_STRING,
          STRING_BYTE_SIZE,
          STRING_CODE_POINT_SIZE,
          STRING_GRAPHEME_SIZE,
          STRING_CODE_POINTS,
          STRING_GRAPHEMES,
          STRING_SLICE_CODE_POINTS,
          STRING_SPLIT,
          STRING_IS_BLANK,
          STRING_IS_EMPTY,
          STRING_CONTAINS,
          STRING_STARTS_WITH,
          STRING_ENDS_WITH,
          STRING_SLICE_GRAPHEMES,
          STRING_REPLACE,
          STRING_REPLACE_FIRST,
          STRING_TRIM,
          STRING_TRIM_START,
          STRING_TRIM_END,
          STRING_TO_LOWERCASE,
          STRING_TO_UPPERCASE,
          STRING_EQUALS_IGNORE_CASE_ASCII,
          STRING_COMPARE_CODE_POINTS,
          STRING_NORMALIZE_NFC,
          STRING_NORMALIZE_NFD,
          STRING_NORMALIZE_NFKC,
          STRING_NORMALIZE_NFKD,
          STRING_IS_NORMALIZED_NFC,
          STRING_IS_NORMALIZED_NFD,
          STRING_IS_NORMALIZED_NFKC,
          STRING_IS_NORMALIZED_NFKD,
          CODE_POINT_SCALAR_VALUE,
          CODE_POINT_IS_DECIMAL_DIGIT,
          CODE_POINT_IS_LETTER,
          CODE_POINT_IS_WHITESPACE,
          CODE_POINT_IS_UPPERCASE,
          CODE_POINT_IS_LOWERCASE,
          CODE_POINT_IS_ASCII_DIGIT,
          CODE_POINT_ASCII_DIGIT_VALUE ->
          TextIntrinsicDispatcher.resolve(intrinsic);
      case RANGE_CONSTRUCT,
          ARRAY_CONSTRUCT,
          LIST_CONSTRUCT,
          MAP_CONSTRUCT,
          SET_CONSTRUCT,
          STACK_CONSTRUCT,
          QUEUE_CONSTRUCT,
          DEQUE_CONSTRUCT,
          PAIR_CONSTRUCT,
          SIZE,
          IS_EMPTY,
          LIST_ADD,
          LIST_GET,
          LIST_REMOVE_AT,
          ARRAY_FILLED,
          ARRAY_LAST,
          ARRAY_REVERSED,
          LIST_FILLED,
          LIST_LAST,
          LIST_REMOVE_LAST,
          LIST_REVERSED,
          MAP_PUT,
          MAP_GET,
          MAP_CONTAINS_KEY,
          MAP_REMOVE,
          SET_ADD,
          SET_CONTAINS,
          SET_REMOVE,
          STACK_PUSH,
          STACK_POP,
          STACK_PEEK,
          QUEUE_ADD,
          QUEUE_REMOVE,
          QUEUE_PEEK,
          DEQUE_ADD_FIRST,
          DEQUE_ADD_LAST,
          DEQUE_REMOVE_FIRST,
          DEQUE_REMOVE_LAST,
          DEQUE_PEEK_FIRST,
          DEQUE_PEEK_LAST,
          PAIR_FIRST_READ,
          PAIR_SECOND_READ,
          PAIR_FIRST_WRITE,
          PAIR_SECOND_WRITE,
          ARRAY_INDEX_READ,
          LIST_INDEX_READ,
          MAP_INDEX_READ,
          ARRAY_INDEX_WRITE,
          LIST_INDEX_WRITE,
          MAP_INDEX_WRITE,
          ARRAY_ITERATOR,
          LIST_ITERATOR,
          MAP_ITERATOR,
          SET_ITERATOR,
          STACK_ITERATOR,
          QUEUE_ITERATOR,
          DEQUE_ITERATOR,
          RANGE_ITERATOR,
          ITERATOR_HAS_NEXT,
          ITERATOR_NEXT ->
          CollectionIntrinsicDispatcher.resolve(intrinsic);
      case IO_BYTES_CREATE,
          IO_BYTES_SIZE,
          IO_BYTES_AT,
          IO_BYTES_SLICE,
          IO_BYTES_TO_ARRAY,
          IO_BYTES_JOIN,
          IO_TEXT_ENCODE_UTF8,
          IO_TEXT_DECODE_UTF8,
          IO_USE ->
          IoIntrinsicDispatcher.resolve(intrinsic);
      case TASK_TERMINATION,
          TASK_START,
          TASK_CONTINUE,
          JAR_TASK_AWAIT,
          JAR_TASK_CANCEL,
          JAR_TASK_COMPLETED,
          JAR_TASK_CLOSE ->
          JarTaskIntrinsicDispatcher.resolve(intrinsic);
      case FILE_OPEN_READ,
          FILE_READER_READ,
          FILE_OPEN_WRITE,
          FILE_WRITER_WRITE,
          FILE_WRITER_FLUSH,
          FILE_WRITER_SYNC,
          FILE_CLOSE ->
          FileIntrinsicDispatcher.resolve(intrinsic);
      case HTTP_SEND,
          HTTP_RESPONSE_STATUS,
          HTTP_RESPONSE_HEADERS,
          HTTP_RESPONSE_READ,
          HTTP_RESPONSE_CLOSE ->
          HttpIntrinsicDispatcher.resolve(intrinsic);
      case WS_CONNECT,
          WS_SEND_TEXT,
          WS_SEND_BINARY,
          WS_PING,
          WS_RECEIVE,
          WS_FINISH,
          WS_CLOSE,
          WS_SUBPROTOCOL ->
          WebSocketIntrinsicDispatcher.resolve(intrinsic);
    };
  }
}
