import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { execFileSync } from 'node:child_process';
import { BaselineStore, prepareBaseline } from './native-baseline-store.mjs';
import { compareNativeSizeSets } from './compare-native-size.mjs';
import { report } from './fixtures/native-size-report.mjs';

test('durable Git baseline validates evidence, preserves history and rejects stale publication', t => {
  const root = mkdtempSync(join(tmpdir(), 'norm-baseline-store-'));
  t.after(() => rmSync(root, { recursive: true, force: true }));
  const remote = join(root, 'remote.git');
  execFileSync('git', ['init', '--bare', remote], { stdio: 'pipe' });
  const candidate = join(root, 'candidate');
  mkdirSync(candidate);
  const fixture = report(join(candidate, 'sample'));
  const identity = { repository: 'normlanguage/Norm', workflowId: 7, platform: 'Linux-X64' };
  const provenance = { ...identity, runId: 12, sourceSha: 'a'.repeat(40), branch: 'main', reason: 'initial baseline' };
  const first = new BaselineStore(remote, identity);
  const stale = new BaselineStore(remote, identity);
  t.after(() => { first.close(); stale.close(); });
  assert.equal(first.load(), undefined);
  assert.equal(stale.load(), undefined);
  const proposal = join(root, 'proposal');
  prepareBaseline(candidate, proposal, { ...provenance, parent: null });
  const sha = first.publish(proposal);
  assert.match(sha, /^[a-f0-9]{40}$/);
  const staleProposal = join(root, 'stale');
  prepareBaseline(candidate, staleProposal, { ...provenance, runId: 99, parent: null });
  assert.throws(() => stale.publish(staleProposal), /changed|stale|rejected/i);
  const next = new BaselineStore(remote, identity);
  t.after(() => next.close());
  const baseline = next.load();
  assert.equal(compareNativeSizeSets(baseline.reports, candidate).passed, true);
  const reset = join(root, 'reset');
  prepareBaseline(candidate, reset, { ...provenance, runId: 13, parent: sha, reason: 'explicit reset' });
  const updated = next.publish(reset);
  assert.equal(execFileSync('git', ['--git-dir', remote, 'rev-parse', `${updated}^`], { encoding: 'utf8' }).trim(), sha);
  fixture.documents['size.json'].deliveryBytes++;
  fixture.save();
  assert.throws(() => prepareBaseline(candidate, join(root, 'invalid'), { ...provenance, parent: updated }), /delivery/i);
  writeFileSync(join(reset, 'reports/sample/size.json'), '{}');
  const corrupt = new BaselineStore(remote, identity);
  t.after(() => corrupt.close());
  corrupt.load();
  assert.throws(() => corrupt.publish(reset));
  writeFileSync(join(corrupt.directory, 'reports/sample/size.json'), '{}');
  corrupt.git(['add', 'reports/sample/size.json']);
  corrupt.git(['commit', '--quiet', '-m', 'Invalid evidence fixture']);
  corrupt.git(['push', 'origin', `HEAD:${corrupt.ref}`]);
  const unreadable = new BaselineStore(remote, identity);
  t.after(() => unreadable.close());
  assert.throws(() => unreadable.load(), /size report/i);
});
